from typing import Dict, Any
from flowweaver.sdk import Node, Port, Parameter, ExecutionContext, TabularDataset

class CustomProcessingNode(Node):
    id = "text_utils_processor"
    label = "Custom Processor"
    category = "Transform"
    description = "A custom node template generated by FlowWeaver CLI."
    icon = "Wand2"
    color = "#7a4fc6"
    inputs = [Port(id="in", label="rows", type="tabular", required=True)]
    outputs = [Port(id="out", label="rows", type="tabular")]
    params_schema = [
        Parameter(key="suffix", label="Text suffix", type="text", default="_processed"),
    ]

    def execute(self, inputs: Dict[str, Any], ctx: ExecutionContext) -> Dict[str, Any]:
        dataset = inputs.get("in")
        if not dataset:
            return {"out": TabularDataset([], columns=[])}
            
        columns = dataset.columns()
        rows = dataset.to_list()
        suffix = ctx.parameters.get("suffix", "_processed")
        
        ctx.log(f"Appending suffix '{suffix}' to all cell values.")
        
        processed_rows = []
        for row in rows:
            new_row = {}
            for k, v in row.items():
                new_row[k] = f"{v}{suffix}"
            processed_rows.append(new_row)
            
        return {"out": TabularDataset(processed_rows, columns=columns)}
