from typing import Optional

import sys
import argparse
import json
import tarfile
import hashlib
import importlib.util

def create_plugin(name: str):
    """Generates a new plugin folder structure based on the platform template."""
    safe_name = name.lower().replace("-", "_").replace(" ", "_")
    base_path = os.path.join(os.getcwd(), name)
    
    if os.path.exists(base_path):
        print(f"Error: Directory '{name}' already exists.")
        sys.exit(1)
        
    print(f"Creating plugin template at: {base_path}...")
    
    # Create directories
    pkg_path = os.path.join(base_path, safe_name)
    os.makedirs(pkg_path, exist_ok=True)
    
    # Write plugin.yaml configuration
    plugin_yaml = f"""id: {safe_name}
name: {name.replace('_', ' ').replace('-', ' ').title()}
version: 0.1.0
author: Developer
description: A custom data processing plugin for FlowWeaver.
nodes:
  - {safe_name}.nodes.CustomProcessingNode
"""
    with open(os.path.join(base_path, "plugin.yaml"), "w") as f:
        f.write(plugin_yaml.strip() + "\n")
        
    # Write requirements.txt
    with open(os.path.join(base_path, "requirements.txt"), "w") as f:
        f.write("# Add additional plugin pip requirements here\n")
        
    # Write package __init__.py
    with open(os.path.join(pkg_path, "__init__.py"), "w") as f:
        f.write(f"# {name} package\n")
        
    # Write package nodes.py with a sample Node implementation
    nodes_py = f"""from typing import Dict, Any
from flowweaver.sdk import Node, Port, Parameter, ExecutionContext, TabularDataset

class CustomProcessingNode(Node):
    id = "{safe_name}_processor"
    label = "Custom Processor"
    category = "Transform"
    description = "A custom node template generated by FlowWeaver CLI."
    icon = "Wand2"
    color = "#7a4fc6"
    inputs = [Port(id="in", label="rows", type="tabular", required=True)]
    outputs = [Port(id="out", label="rows", type="tabular")]
    params_schema = [
        Parameter(key="suffix", label="Text suffix", type="text", default="_processed"),
    ]

    def execute(self, inputs: Dict[str, Any], ctx: ExecutionContext) -> Dict[str, Any]:
        dataset = inputs.get("in")
        if not dataset:
            return {{"out": TabularDataset([], columns=[])}}
            
        columns = dataset.columns()
        rows = dataset.to_list()
        suffix = ctx.parameters.get("suffix", "_processed")
        
        ctx.log(f"Appending suffix '{{suffix}}' to all cell values.")
        
        processed_rows = []
        for row in rows:
            new_row = {{}}
            for k, v in row.items():
                new_row[k] = f"{{v}}{{suffix}}"
            processed_rows.append(new_row)
            
        return {{"out": TabularDataset(processed_rows, columns=columns)}}
"""
    with open(os.path.join(pkg_path, "nodes.py"), "w") as f:
        f.write(nodes_py.strip() + "\n")
        
    # Write README.md
    readme = f"""# {name}

A custom FlowWeaver plugin.

## Installation

Register this plugin directory inside the FlowWeaver plugins directory, or deploy it.
"""
    with open(os.path.join(base_path, "README.md"), "w") as f:
        f.write(readme.strip() + "\n")
        
    print(f"Successfully generated plugin template '{name}'!")
    print("Folder contents:")
    print(f"  - {name}/plugin.yaml")
    print(f"  - {name}/requirements.txt")
    print(f"  - {name}/{safe_name}/nodes.py")


def create_node(name: str, category: str):
    """Scaffolds a single node package with tests, benchmarks, and category-specific templates."""
    safe_name = name.lower().replace("-", "_").replace(" ", "_")
    base_path = os.path.join(os.getcwd(), name)
    
    if os.path.exists(base_path):
        print(f"Error: Directory '{name}' already exists.")
        sys.exit(1)
        
    print(f"Creating modular {category} node template at: {base_path}...")
    
    # Create directory structure
    dirs = [
        "",
        "core",
        "utils",
        "tests",
        "examples",
        "benchmarks",
        "data"
    ]
    for d in dirs:
        os.makedirs(os.path.join(base_path, d), exist_ok=True)
        if d in ["core", "utils", "tests", "benchmarks"]:
            with open(os.path.join(base_path, d, "__init__.py"), "w") as f:
                f.write(f"# {d} package\n")

    # Generate sample datasets
    sample_csv = "id,name,score\n1,Alpha,92.5\n2,Beta,78.1\n3,Gamma,88.0\n4,Delta,62.4\n"
    with open(os.path.join(base_path, "data", "sample.csv"), "w") as f:
        f.write(sample_csv)

    sample_json = '[\n  {"id": 1, "text": "FlowWeaver is awesome", "label": "pos"},\n  {"id": 2, "text": "This preprocessor is fast", "label": "pos"},\n  {"id": 3, "text": "Errors are descriptive", "label": "neutral"}\n]\n'
    with open(os.path.join(base_path, "data", "sample.json"), "w") as f:
        f.write(sample_json)

    # Setup category specific parameters, inputs/outputs, and implementation templates
    if category == "Loader":
        inputs_str = ""
        outputs_str = "    out = Output.tabular(label=\"Loaded Rows\")\n"
        params_str = '    file_path = Param.file(label="CSV File Path", default="data/sample.csv", accept=".csv", description="Path to the CSV dataset file")\n    delimiter = Param.select(label="Delimiter", default=",", options=[{"label": "Comma", "value": ","}, {"label": "Semicolon", "value": ";"}])'
        service_call = "return {'out': service.run(ctx.parameters.get('file_path'), ctx.parameters.get('delimiter', ','), ctx)}"
        
        core_alg = """import csv
from flowweaver.sdk import TabularDataset

def process_data(file_path, delimiter, ctx=None):
    \"\"\"Reads a CSV file and loads it into a TabularDataset.\"\"\"
    if ctx:
        ctx.log(f"Reading dataset from path: {file_path}")
    
    rows = []
    columns = []
    try:
        with open(file_path, mode='r', encoding='utf-8') as f:
            reader = csv.reader(f, delimiter=delimiter)
            columns = next(reader) if reader else []
            for row in reader:
                if len(row) == len(columns):
                    rows.append(dict(zip(columns, row)))
    except FileNotFoundError:
        # Fallback to local default file path if relative path runs inside project root
        alt_path = "data/sample.csv"
        with open(alt_path, mode='r', encoding='utf-8') as f:
            reader = csv.reader(f, delimiter=delimiter)
            columns = next(reader) if reader else []
            for row in reader:
                if len(row) == len(columns):
                    rows.append(dict(zip(columns, row)))
                    
    return TabularDataset(rows, columns=columns)
"""
        basic_example = {"file_path": "data/sample.csv", "delimiter": ","}

    elif category == "Filter":
        inputs_str = "    in_data = Input.tabular(label=\"Source Rows\")\n"
        outputs_str = "    out = Output.tabular(label=\"Filtered Rows\")\n"
        params_str = '    column = Param.column(label="Filter Column", default="score", description="Column to apply comparison filter")\n    min_value = Param.number(label="Min Threshold", default=80.0, description="Keep values greater than or equal to this limit")'
        service_call = "in_val = inputs.get('in_data')\n        return {'out': service.run(in_val, ctx.parameters.get('column'), ctx.parameters.get('min_value'), ctx)}"
        
        core_alg = """from flowweaver.sdk import TabularDataset

def process_data(dataset, column, min_value, ctx=None):
    \"\"\"Filters dataset rows matching comparison constraint.\"\"\"
    if not dataset:
        return TabularDataset([], columns=[])
        
    rows = dataset.to_list()
    filtered_rows = []
    
    if ctx:
        ctx.log(f"Filtering {len(rows)} rows on column '{column}' >= {min_value}")
        
    for r in rows:
        try:
            val = float(r.get(column, 0))
            if val >= float(min_value):
                filtered_rows.append(r)
        except ValueError:
            # Skip rows with non-numeric fields
            continue
            
    return TabularDataset(filtered_rows, columns=dataset.columns())
"""
        basic_example = {"column": "score", "min_value": 80.0}

    elif category == "Transform":
        inputs_str = "    in_data = Input.tabular(label=\"Source Rows\")\n"
        outputs_str = "    out = Output.tabular(label=\"Modified Rows\")\n"
        params_str = '    target_column = Param.column(label="Column to Edit", default="name")\n    suffix = Param.text(label="Suffix String", default=" [Validated]", description="String to append to column values")'
        service_call = "in_val = inputs.get('in_data')\n        return {'out': service.run(in_val, ctx.parameters.get('target_column'), ctx.parameters.get('suffix'), ctx)}"
        
        core_alg = """from flowweaver.sdk import TabularDataset

def process_data(dataset, target_col, suffix, ctx=None):
    \"\"\"Appends a string suffix to a targeted dataset column.\"\"\"
    if not dataset:
        return TabularDataset([], columns=[])
        
    rows = dataset.to_list()
    processed_rows = []
    
    for r in rows:
        new_row = r.copy()
        if target_col in new_row:
            new_row[target_col] = f"{new_row[target_col]}{suffix}"
        processed_rows.append(new_row)
        
    if ctx:
        ctx.log(f"Appended suffix '{suffix}' to column '{target_col}' across {len(processed_rows)} rows")
        
    return TabularDataset(processed_rows, columns=dataset.columns())
"""
        basic_example = {"target_column": "name", "suffix": " [Validated]"}

    elif category == "Exporter":
        inputs_str = "    in_data = Input.any(label=\"Data Input\")\n"
        outputs_str = ""
        params_str = '    output_path = Param.file(label="Save Destination", default="data/exported.json", accept=".json", description="Target path to serialize records")'
        service_call = "in_val = inputs.get('in_data')\n        service.run(in_val, ctx.parameters.get('output_path'), ctx)\n        return {}"
        
        core_alg = """import json

def process_data(dataset, output_path, ctx=None):
    \"\"\"Serializes the dataset records into a JSON document.\"\"\"
    if not dataset:
        return
        
    records = dataset.to_list()
    if ctx:
        ctx.log(f"Writing {len(records)} records to destination: {output_path}")
        
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(records, f, indent=2)
"""
        basic_example = {"output_path": "data/exported.json"}

    elif category == "AI":
        inputs_str = "    in_text = Input.text(label=\"Source Text\")\n"
        outputs_str = "    out = Output.text(label=\"AI Output\")\n"
        params_str = '    prompt_prefix = Param.textarea(label="Prompt Prefix", default="Summarize the following text:\\n")'
        service_call = "in_val = inputs.get('in_text')\n        return {'out': service.run(in_val, ctx.parameters.get('prompt_prefix'), ctx)}"
        
        core_alg = """from flowweaver.sdk import TabularDataset

def process_data(dataset, prompt_prefix, ctx=None):
    \"\"\"Simulates AI text processing.\"\"\"
    if not dataset:
        return TabularDataset([], columns=["text"])
        
    rows = dataset.to_list()
    output_rows = []
    
    for r in rows:
        text = r.get("text", "")
        # Dummy AI translation/summary simulation
        summary = f"{prompt_prefix}{text[:15]}..."
        output_rows.append({"original": text, "ai_result": summary})
        
    return TabularDataset(output_rows, columns=["original", "ai_result"])
"""
        basic_example = {"prompt_prefix": "Summarize: "}
    else:
        inputs_str = "    in_data = Input.any()\n"
        outputs_str = "    out = Output.any()\n"
        params_str = '    example_param = Param.text(label="Example Param", default="value")'
        service_call = "in_val = inputs.get('in_data')\n        return {'out': service.run(in_val, ctx.parameters.get('example_param'), ctx)}"
        
        core_alg = """def process_data(data, param_val, ctx=None):
    if ctx:
        ctx.log(f"Processing data with param: {param_val}")
    return data
"""
        basic_example = {"example_param": "value"}

    class_name = "".join(part.title() for part in safe_name.split("_")) + "Node"
    service_name = "".join(part.title() for part in safe_name.split("_")) + "Service"

    # 1. node.py (Adapter)
    node_py = f"""from typing import Dict, Any
from flowweaver.sdk import Node, Input, Output, Param, node, ExecutionContext
from service import {service_name}

@node(name="{name}", category="{category}")
class {class_name}(Node):
    \"\"\"{name} node adapter. Exposes FlowWeaver interface.
    
    All core computational logic resides in core/ and coordinates via service.py.
    This file must remain under 200 lines and avoid direct OS, network, or DB calls.
    \"\"\"
{inputs_str}{outputs_str}
    # Configuration Parameters
{params_str}

    def execute(self, inputs: Dict[str, Any], ctx: ExecutionContext) -> Dict[str, Any]:
        ctx.log("Delegating execution to Service layer.")
        service = {service_name}()
        {service_call}
"""
    with open(os.path.join(base_path, "node.py"), "w") as f:
        f.write(node_py.strip() + "\n")

    # 2. service.py (Orchestrator)
    service_py = f"""from flowweaver.sdk import ExecutionContext
from core.algorithm import process_data
from utils.helpers import log_info

class {service_name}:
    \"\"\"Service layer coordinating core algorithm logic and helper utilities.
    Runs business logic without knowing about FlowWeaver Node internals.
    \"\"\"
    def run(self, *args, **kwargs):
        ctx = args[-1] if args and isinstance(args[-1], ExecutionContext) else None
        if ctx:
            log_info(ctx, "Orchestrating logic inside Service layer.")
        
        # Unpack params, delegate to core logic
        return process_data(*args[:-1], ctx=ctx)
"""
    with open(os.path.join(base_path, "service.py"), "w") as f:
        f.write(service_py.strip() + "\n")

    # 3. core/algorithm.py (Core)
    with open(os.path.join(base_path, "core", "algorithm.py"), "w") as f:
        f.write(core_alg.strip() + "\n")

    # 4. utils/helpers.py (Helpers)
    helpers_py = f"""def log_info(ctx, message: str):
    \"\"\"Utility helper demonstrating context routing.\"\"\"
    ctx.log(f"[Helper] {{message}}")
"""
    with open(os.path.join(base_path, "utils", "helpers.py"), "w") as f:
        f.write(helpers_py.strip() + "\n")

    # 5. plugin.yaml
    plugin_yaml = f"""id: {safe_name}
name: {name}
nodes:
  - node.{class_name}
"""
    with open(os.path.join(base_path, "plugin.yaml"), "w") as f:
        f.write(plugin_yaml.strip() + "\n")

    # 6. README.md
    readme_md = f"""# {name} Capability Plugin

Auto-generated FlowWeaver Capability Plugin for {name} ({category}).

## Design Structure
Following the FlowWeaver "Node as Adapter" architecture:
- `node.py`: Adapts the capability to FlowWeaver (under 200 lines).
- `service.py`: Orchestrates business logic coordination.
- `core/`: Computational algorithms (independent reusable Python modules).
- `utils/`: Help and auxiliary subroutines.
- `tests/`: Separate node adapter, algorithm, and example regression tests.
"""
    with open(os.path.join(base_path, "README.md"), "w") as f:
        f.write(readme_md.strip() + "\n")

    # 7. tests/
    test_node_py = f"""import json
import os
from flowweaver.sdk import ExecutionContext
from node import {class_name}

def test_node_execute():
    # Test the FlowWeaver Node Adapter interface
    n = {class_name}()
    assert n.category == "{category}"
"""
    with open(os.path.join(base_path, "tests", "test_node.py"), "w") as f:
        f.write(test_node_py.strip() + "\n")

    if category == "Loader":
        test_alg_py = """from core.algorithm import process_data
import os

def test_algorithm_logic():
    # Test the core loader function
    sample_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'sample.csv')
    dataset = process_data(sample_path, ",")
    assert dataset is not None
    assert dataset.row_count() == 4
    assert dataset.columns() == ["id", "name", "score"]
"""
    elif category == "Filter":
        test_alg_py = """from core.algorithm import process_data
from flowweaver.sdk import TabularDataset

def test_algorithm_logic():
    # Test the core filter logic
    data = TabularDataset([{"score": 90}, {"score": 60}], columns=["score"])
    filtered = process_data(data, "score", 80)
    assert filtered.row_count() == 1
    assert filtered.to_list()[0]["score"] == 90
"""
    elif category == "Transform":
        test_alg_py = """from core.algorithm import process_data
from flowweaver.sdk import TabularDataset

def test_algorithm_logic():
    data = TabularDataset([{"name": "Alice"}], columns=["name"])
    transformed = process_data(data, "name", " [Validated]")
    assert transformed.to_list()[0]["name"] == "Alice [Validated]"
"""
    elif category == "Exporter":
        test_alg_py = """from core.algorithm import process_data
from flowweaver.sdk import TabularDataset
import os
import json

def test_algorithm_logic():
    data = TabularDataset([{"id": 1}], columns=["id"])
    out_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'temp_exported.json')
    try:
        process_data(data, out_path)
        assert os.path.exists(out_path)
        with open(out_path) as f:
            exported = json.load(f)
        assert len(exported) == 1
    finally:
        if os.path.exists(out_path):
            os.remove(out_path)
"""
    elif category == "AI":
        test_alg_py = """from core.algorithm import process_data
from flowweaver.sdk import TabularDataset

def test_algorithm_logic():
    data = TabularDataset([{"text": "Sample sentence"}], columns=["text"])
    res = process_data(data, "Prompt: ")
    assert res.to_list()[0]["ai_result"].startswith("Prompt: ")
"""
    else:
        test_alg_py = f"""from core.algorithm import process_data

def test_algorithm_logic():
    result = process_data("test_input", "value")
    assert result == "test_input"
"""
    with open(os.path.join(base_path, "tests", "test_algorithm.py"), "w") as f:
        f.write(test_alg_py.strip() + "\n")

    test_ex_py = f"""import json
import os
from node import {class_name}

def test_examples():
    example_file = os.path.join(os.path.dirname(__file__), '..', 'examples', 'basic.json')
    assert os.path.exists(example_file)
    with open(example_file) as f:
        data = json.load(f)
    assert len(data) > 0
"""
    with open(os.path.join(base_path, "tests", "test_examples.py"), "w") as f:
        f.write(test_ex_py.strip() + "\n")

    # 8. examples
    with open(os.path.join(base_path, "examples", "basic.json"), "w") as f:
        json.dump(basic_example, f, indent=2)
        f.write("\n")
    with open(os.path.join(base_path, "examples", "advanced.json"), "w") as f:
        json.dump(basic_example, f, indent=2)
        f.write("\n")

    # 9. benchmarks/benchmark.py
    if category == "Loader":
        bench_call = "process_data('data/sample.csv', ',')"
    elif category == "Filter":
        bench_call = "from flowweaver.sdk import TabularDataset\\n    data = TabularDataset([{'score': 90}], ['score'])\\n    process_data(data, 'score', 80)"
    elif category == "Transform":
        bench_call = "from flowweaver.sdk import TabularDataset\\n    data = TabularDataset([{'name': 'Alice'}], ['name'])\\n    process_data(data, 'name', ' [Validated]')"
    elif category == "Exporter":
        bench_call = "from flowweaver.sdk import TabularDataset\\n    data = TabularDataset([{'id': 1}], ['id'])\\n    process_data(data, 'data/exported.json')"
    elif category == "AI":
        bench_call = "from flowweaver.sdk import TabularDataset\\n    data = TabularDataset([{'text': 'Sample'}], ['text'])\\n    process_data(data, 'Prefix: ')"
    else:
        bench_call = "process_data('data', 'value')"

    benchmark_py = f"""import time
from core.algorithm import process_data

def run_benchmark():
    print("Running performance benchmark...")
    start = time.time()
    for _ in range(1000):
        {bench_call}
    duration = time.time() - start
    print(f"Completed 1000 runs in {{duration:.4f}}s")

if __name__ == "__main__":
    run_benchmark()
"""
    with open(os.path.join(base_path, "benchmarks", "benchmark.py"), "w") as f:
        f.write(benchmark_py.strip() + "\n")

    print(f"Successfully generated modular {category} capability plugin '{name}'!")


def _load_node_class(path: str):
    node_file = os.path.join(path, "node.py")
    if not os.path.exists(node_file):
        return None
    sys.path.insert(0, os.path.abspath(path))
    try:
        spec = importlib.util.spec_from_file_location("node_module", node_file)
        if not spec or not spec.loader:
            return None
        node_module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(node_module)
    except Exception as e:
        sys.path.pop(0)
        raise e
    finally:
        sys.path.pop(0)

    from flowweaver.sdk import Node
    
    for name, obj in vars(node_module).items():
        if isinstance(obj, type) and issubclass(obj, Node) and obj is not Node:
            return obj
    return None


def test_node(path: str):
    print(f"Testing node at {path}...")
    examples_path = os.path.join(path, "examples", "basic.json")
    if not os.path.exists(examples_path):
        print(f"Error: examples/basic.json not found in {path}")
        sys.exit(1)

    node_class = _load_node_class(path)
    if not node_class:
        print("Error: Could not find a Node subclass in node.py")
        sys.exit(1)

    with open(examples_path, "r") as f:
        params = json.load(f)

    try:
        instance = node_class()
        class MockCtx:
            def __init__(self, p):
                self.parameters = p
                self.variables = {}
            def log(self, msg):
                print(f"[LOG] {msg}")
        
        ctx = MockCtx(params)
        sys.path.insert(0, os.path.abspath(path))
        try:
            # Set relative path adjustments so loaders resolve "data/sample.csv" relative to target path
            cwd = os.getcwd()
            os.chdir(os.path.abspath(path))
            try:
                instance.execute({}, ctx)
            finally:
                os.chdir(cwd)
        finally:
            sys.path.pop(0)
        print("PASS")
    except Exception as e:
        print(f"FAIL: {e}")
        sys.exit(1)


def lint_node(path: str) -> bool:
    print(f"Linting node at {path}...")
    
    node_file = os.path.join(path, "node.py")
    if not os.path.exists(node_file):
        print(f"Error: node.py not found in {path}")
        return False

    node_class = _load_node_class(path)
    if not node_class:
        print("Error: Could not find a Node subclass in node.py")
        return False

    has_error = False

    # Enforce line limit
    with open(node_file, "r") as f:
        lines = f.readlines()
    if len(lines) > 200:
        print(f"Error: node.py is too long ({len(lines)} lines). Keep it under 200 lines. Move logic to core/.")
        has_error = True

    # Enforce imports restrictions
    forbidden = ["requests", "threading", "sqlite3", "logging", "urllib", "subprocess"]
    for idx, line in enumerate(lines, 1):
        for item in forbidden:
            if f"import {item}" in line or f"from {item}" in line:
                print(f"Error: node.py:L{idx} contains import of '{item}'. Use ExecutionContext services instead.")
                has_error = True

    for attr in ["id", "label", "category", "description"]:
        if not hasattr(node_class, attr) or not getattr(node_class, attr):
            print(f"Error: Node is missing '{attr}'")
            has_error = True

    category = getattr(node_class, "category", "")
    outputs = getattr(node_class, "outputs", [])
    if category != "Exporter" and not outputs:
        print("Error: Node must have at least one output port unless category is Exporter")
        has_error = True

    if not hasattr(node_class, "execute") or not callable(getattr(node_class, "execute")):
        print("Error: Node is missing execute() method")
        has_error = True

    params_schema = getattr(node_class, "params_schema", [])
    for p in params_schema:
        for pattr in ["key", "label", "type"]:
            if not hasattr(p, pattr) or getattr(p, pattr) is None:
                print(f"Error: Parameter missing '{pattr}'")
                has_error = True

    readme_path = os.path.join(path, "README.md")
    if not os.path.exists(readme_path):
        print("Warning: Missing documentation (README.md)")

    examples_path = os.path.join(path, "examples")
    if not os.path.exists(examples_path) or not os.listdir(examples_path):
        print("Warning: Missing examples in examples/")

    if has_error:
        print("Linting failed with errors.")
        return False
    else:
        print("Linting passed.")
        return True


def generate_docs(path: str):
    """Automatically generates markdown documentation from node metadata."""
    node_class = _load_node_class(path)
    if not node_class:
        print("Error: Could not load node class to generate docs.")
        sys.exit(1)

    node_id = getattr(node_class, "id", "unknown")
    node_label = getattr(node_class, "label", "Unknown Node")
    node_category = getattr(node_class, "category", "Custom")
    node_desc = getattr(node_class, "description", "")
    inputs = getattr(node_class, "inputs", [])
    outputs = getattr(node_class, "outputs", [])
    params = getattr(node_class, "params_schema", [])
    docs_text = getattr(node_class, "documentation", "")

    md = []
    md.append(f"# Node Reference: {node_label}")
    md.append(f"**ID**: `{node_id}`  |  **Category**: `{node_category}`")
    md.append("")
    md.append(f"## Description")
    md.append(node_desc or "No description provided.")
    md.append("")

    md.append("## Interface Ports")
    if inputs:
        md.append("### Inputs")
        for port in inputs:
            req_str = " (Required)" if getattr(port, "required", False) else ""
            md.append(f"- **{port.id}**: `{port.type}` — {port.label}{req_str}")
    else:
        md.append("- No input ports.")

    md.append("")
    if outputs:
        md.append("### Outputs")
        for port in outputs:
            md.append(f"- **{port.id}**: `{port.type}` — {port.label}")
    else:
        md.append("- No output ports.")
    md.append("")

    md.append("## Configuration Parameters")
    if params:
        md.append("| Parameter Key | Label | Type | Default | Description |")
        md.append("|---|---|---|---|---|")
        for p in params:
            desc = getattr(p, "description", "") or ""
            default_val = getattr(p, "default", "")
            if default_val is None:
                default_val = "*None*"
            md.append(f"| `{p.key}` | {p.label} | `{p.type}` | `{default_val}` | {desc} |")
    else:
        md.append("No configuration parameters.")
    md.append("")

    if docs_text:
        md.append("## Additional Documentation")
        md.append(docs_text)
        md.append("")

    output_file = os.path.join(path, "docs.md")
    with open(output_file, "w") as f:
        f.write("\n".join(md).strip() + "\n")
    print(f"Documentation generated successfully at: {output_file}")


def package_plugin(path: str):
    print(f"Packaging plugin at {path}...")
    
    # Validation step before packaging (Phase 2 constraint)
    print("Verifying node constraints and style rules before packaging...")
    if not lint_node(path):
        print("Error: Packaging aborted due to linting validation failures.")
        sys.exit(1)

    plugin_yaml_path = os.path.join(path, "plugin.yaml")
    if not os.path.exists(plugin_yaml_path):
        print(f"Error: plugin.yaml not found in {path}")
        sys.exit(1)

    plugin_name = os.path.basename(os.path.abspath(path))
    tar_filename = f"{plugin_name}.tar.gz"
    
    with tarfile.open(tar_filename, "w:gz") as tar:
        tar.add(path, arcname=plugin_name)
        
    sha256_hash = hashlib.sha256()
    with open(tar_filename, "rb") as f:
        for byte_block in iter(lambda: f.read(4096), b""):
            sha256_hash.update(byte_block)
            
    manifest = {
        "archive": tar_filename,
        "checksum": sha256_hash.hexdigest()
    }
    
    with open("manifest.json", "w") as f:
        json.dump(manifest, f, indent=2)
        
    print(f"Successfully packaged archive with SHA-256 manifest.")
    print(f"Output path: {os.path.abspath(tar_filename)}")


def compile_pipeline(pipeline_path: str, output_path: Optional[str] = None):
    """Compiles a visual pipeline.json file into a standalone, production-ready pipeline.py script."""
    if not os.path.exists(pipeline_path):
        print(f"Error: Pipeline file '{pipeline_path}' not found.")
        sys.exit(1)

    try:
        with open(pipeline_path, "r", encoding="utf-8") as f:
            pipeline_data = json.load(f)
    except Exception as e:
        print(f"Error reading pipeline file: {e}")
        sys.exit(1)

    try:
        from app.compiler.compiler import PipelineCompiler, CompilerConfig
    except ImportError:
        print("Error: FlowWeaver compiler package could not be loaded.")
        sys.exit(1)

    out_dir = os.path.dirname(os.path.abspath(output_path)) if output_path else os.getcwd()
    out_name = os.path.basename(output_path) if output_path else "pipeline.py"

    config = CompilerConfig(output_dir=out_dir, script_name=out_name)
    res = PipelineCompiler.compile(pipeline_data, config)

    if res.success:
        print(f"✔ Pipeline successfully compiled to: {res.script_path}")
    else:
        print("❌ Pipeline compilation failed:")
        for err in res.errors:
            print(f"  - {err}")
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(description="FlowWeaver CLI developer assistant tool.")
    subparsers = parser.add_subparsers(dest="command", required=True)
    
    compile_parser = subparsers.add_parser("compile", help="Compiles a visual pipeline JSON into a runnable Python script.")
    compile_parser.add_argument("pipeline", type=str, help="Path to input pipeline.json file.")
    compile_parser.add_argument("--output", "-o", type=str, default=None, help="Output path for compiled pipeline.py script.")

    create_plugin_parser = subparsers.add_parser("create-plugin", help="Scaffold a new custom plugin template.")
    create_plugin_parser.add_argument("name", type=str, help="Name of the plugin directory to create.")

    create_node_parser = subparsers.add_parser("create-node", help="Scaffolds a single node capability package with tests and examples.")
    create_node_parser.add_argument("name", type=str, help="Name of the node directory to create.")
    create_node_parser.add_argument("--category", type=str, required=True, choices=["Loader", "Transform", "Filter", "Exporter", "AI", "Custom"], help="Template category for the node.")

    test_parser = subparsers.add_parser("test-node", help="Runs a node against its example fixtures.")
    test_parser.add_argument("path", type=str, help="Path to the node directory.")

    lint_parser = subparsers.add_parser("lint-node", help="Validates node metadata completeness and adapter architecture rules.")
    lint_parser.add_argument("path", type=str, help="Path to the node directory.")

    doc_parser = subparsers.add_parser("generate-docs", help="Automatically generates markdown documentation for the node.")
    doc_parser.add_argument("path", type=str, help="Path to the node directory.")

    package_parser = subparsers.add_parser("package-plugin", help="Builds a distributable archive.")
    package_parser.add_argument("path", type=str, help="Path to the plugin directory.")
    
    args = parser.parse_args()
    
    if args.command == "compile":
        compile_pipeline(args.pipeline, args.output)
    elif args.command == "create-plugin":
        create_plugin(args.name)
    elif args.command == "create-node":
        create_node(args.name, args.category)
    elif args.command == "test-node":
        test_node(args.path)
    elif args.command == "lint-node":
        if not lint_node(args.path):
            sys.exit(1)
    elif args.command == "generate-docs":
        generate_docs(args.path)
    elif args.command == "package-plugin":
        package_plugin(args.path)

if __name__ == "__main__":
    main()

