import { useState, useMemo } from "react";
import { createPortal } from "react-dom";
import { X, Copy, Download, Code2, Check, Sparkles } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { toast } from "sonner";

interface CompileViewerModalProps {
  isOpen: boolean;
  onClose: () => void;
  script: string;
  pipelineName: string;
}

/** Minimal Python syntax highlighting using spans + CSS classes. */
function highlightPython(code: string): string {
  return code
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    // Triple-quoted docstrings
    .replace(/("""[\s\S]*?""")/g, '<span class="py-string">$1</span>')
    // Comments (# ...)
    .replace(/(#.*)/gm, '<span class="py-comment">$1</span>')
    // Single/double quoted strings (not inside comments)
    .replace(/(?<!py-comment">.*?)('(?:[^'\\]|\\.)*'|"(?:[^"\\]|\\.)*")/g, '<span class="py-string">$1</span>')
    // Keywords
    .replace(
      /\b(def|class|import|from|return|if|elif|else|for|while|with|as|try|except|finally|raise|pass|break|continue|and|or|not|in|is|None|True|False|__name__|__main__)\b/g,
      '<span class="py-keyword">$1</span>'
    )
    // Built-in functions
    .replace(
      /\b(print|len|range|int|str|float|list|dict|set|tuple|type|isinstance|open|sorted|map|filter|zip|enumerate)\b(?=\s*\()/g,
      '<span class="py-builtin">$1</span>'
    )
    // Function calls (word followed by open paren)
    .replace(
      /\b([a-zA-Z_][a-zA-Z0-9_]*)\s*(?=\()/g,
      '<span class="py-func">$1</span>'
    )
    // Decorators
    .replace(/^(\s*@\w+)/gm, '<span class="py-decorator">$1</span>');
}


export function CompileViewerModal({ isOpen, onClose, script, pipelineName }: CompileViewerModalProps) {
  const [copied, setCopied] = useState(false);

  const highlighted = useMemo(() => highlightPython(script || ""), [script]);
  const lineCount = (script || "").split("\n").length;

  const handleCopy = () => {
    navigator.clipboard.writeText(script);
    setCopied(true);
    toast.success("Compiled Python script copied to clipboard!");
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([script], { type: "text/x-python" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${pipelineName.replace(/\s+/g, "_").toLowerCase()}_pipeline.py`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
    toast.success("Downloaded pipeline.py!");
  };

  // Mount at body root level using createPortal to bypass Toolbar constraints and fill available screen space
  return createPortal(
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-[999] flex items-center justify-center p-6 bg-black/80 backdrop-blur-md">
          {/* Dimmed backdrop area wrapper */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="absolute inset-0"
            onClick={onClose}
          />

          {/* IDE Modal Container: 85vh height, 6xl width */}
          <motion.div
            initial={{ opacity: 0, y: 15, scale: 0.98 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 15, scale: 0.98 }}
            transition={{ duration: 0.2, ease: "easeOut" }}
            className="relative w-full max-w-6xl h-[85vh] flex flex-col rounded-xl bg-zinc-950 border border-zinc-800 shadow-2xl overflow-hidden z-10"
          >
            {/* Header / Workspace Toolbar */}
            <div className="flex items-center justify-between px-6 py-4 border-b border-zinc-800 bg-zinc-900/50 flex-shrink-0">
              <div className="flex items-center gap-3">
                <div className="h-9 w-9 rounded-lg bg-purple-500/10 border border-purple-500/20 flex items-center justify-center text-purple-400">
                  <Code2 size={18} />
                </div>
                <div>
                  <h3 className="text-sm font-semibold text-zinc-100 tracking-tight flex items-center gap-2">
                    {pipelineName.replace(/\s+/g, "_").toLowerCase()}_pipeline.py
                    <span className="text-[10px] font-normal text-purple-400 px-2 py-0.5 rounded-full bg-purple-500/10 border border-purple-500/20">Standalone Executable</span>
                  </h3>
                  <p className="text-[11px] text-zinc-400">Standalone pre-processing build package generated by visual compiler</p>
                </div>
              </div>

              <div className="flex items-center gap-2">
                <button
                  onClick={handleCopy}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded bg-zinc-800 hover:bg-zinc-700 border border-zinc-700 text-xs text-zinc-200 font-medium transition-colors"
                >
                  {copied ? <Check size={14} className="text-emerald-400" /> : <Copy size={14} />}
                  {copied ? "Copied" : "Copy Code"}
                </button>

                <button
                  onClick={handleDownload}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded bg-purple-600 hover:bg-purple-500 text-xs text-white font-medium transition-colors shadow-lg shadow-purple-500/20"
                >
                  <Download size={14} />
                  Download .py
                </button>

                <button
                  onClick={onClose}
                  className="p-1.5 rounded hover:bg-zinc-800 text-zinc-400 hover:text-zinc-200 transition-colors ml-2"
                >
                  <X size={16} />
                </button>
              </div>
            </div>

            {/* Code Editor Panel */}
            <div className="flex-1 overflow-auto bg-[#0d1117] min-h-0 w-full">
              <div className="flex min-w-0 min-h-full w-full">
                {/* Line Numbers Gutter */}
                <div className="sticky left-0 flex-shrink-0 select-none py-6 pl-4 pr-3 text-right font-mono text-[11px] leading-[1.65rem] text-zinc-600 border-r border-zinc-800 bg-[#0d1117] min-h-full">
                  {Array.from({ length: lineCount }, (_, i) => (
                    <div key={i}>{i + 1}</div>
                  ))}
                </div>

                {/* Editor Pre Container */}
                <pre className="flex-1 py-6 px-5 font-mono text-[13px] leading-[1.65rem] text-zinc-300 whitespace-pre overflow-x-auto min-w-0 selection:bg-purple-500/30">
                  <code dangerouslySetInnerHTML={{ __html: highlighted }} />
                </pre>
              </div>
            </div>

            {/* Editor Status bar */}
            <div className="px-6 py-2.5 border-t border-zinc-800 bg-zinc-900/50 flex items-center justify-between text-[11px] text-zinc-500 flex-shrink-0">
              <span className="flex items-center gap-1.5 font-medium">
                <Sparkles size={13} className="text-purple-400 animate-pulse" />スタンドアロン standalone script — executable under Python 3.10+
              </span>
              <span className="font-mono">Line {lineCount}, Col 1 • UTF-8 • Python</span>
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>,
    document.body
  );
}
