import os

sdk_dir = "packages/flowweaver_sdk"

# 1. Create flowweaver/sdk/cli.py implementing the plugin template generator CLI
cli_py = """import os
import sys
import argparse

def create_plugin(name: str):
    \"\"\"Generates a new plugin folder structure based on the platform template.\"\"\"
    safe_name = name.lower().replace("-", "_").replace(" ", "_")
    base_path = os.path.join(os.getcwd(), name)
    
    if os.path.exists(base_path):
        print(f"Error: Directory '{name}' already exists.")
        sys.exit(1)
        
    print(f"Creating plugin template at: {base_path}...")
    
    # Create directories
    pkg_path = os.path.join(base_path, safe_name)
    os.makedirs(pkg_path, exist_ok=True)
    
    # Write plugin.yaml configuration
    plugin_yaml = f\"\"\"id: {safe_name}
name: {name.replace('_', ' ').replace('-', ' ').title()}
version: 0.1.0
author: Developer
description: A custom data processing plugin for FlowWeaver.
nodes:
  - {safe_name}.nodes.CustomProcessingNode
\"\"\"
    with open(os.path.join(base_path, "plugin.yaml"), "w") as f:
        f.write(plugin_yaml.strip() + "\\n")
        
    # Write requirements.txt
    with open(os.path.join(base_path, "requirements.txt"), "w") as f:
        f.write("# Add additional plugin pip requirements here\\n")
        
    # Write package __init__.py
    with open(os.path.join(pkg_path, "__init__.py"), "w") as f:
        f.write(f"# {name} package\\n")
        
    # Write package nodes.py with a sample Node implementation
    nodes_py = f\"\"\"from typing import Dict, Any
from flowweaver.sdk import Node, Port, Parameter, ExecutionContext, TabularDataset

class CustomProcessingNode(Node):
    id = "{safe_name}_processor"
    label = "Custom Processor"
    category = "Transform"
    description = "A custom node template generated by FlowWeaver CLI."
    icon = "Wand2"
    color = "#7a4fc6"
    inputs = [Port(id="in", label="rows", type="tabular", required=True)]
    outputs = [Port(id="out", label="rows", type="tabular")]
    params_schema = [
        Parameter(key="suffix", label="Text suffix", type="text", default="_processed"),
    ]

    def execute(self, inputs: Dict[str, Any], ctx: ExecutionContext) -> Dict[str, Any]:
        dataset = inputs.get("in")
        if not dataset:
            return {{"out": TabularDataset([], columns=[])}}
            
        columns = dataset.columns()
        rows = dataset.to_list()
        suffix = ctx.parameters.get("suffix", "_processed")
        
        ctx.log(f"Appending suffix '{suffix}' to all cell values.")
        
        processed_rows = []
        for row in rows:
            new_row = {{}}
            for k, v in row.items():
                new_row[k] = f"{{v}}{{suffix}}"
            processed_rows.append(new_row)
            
        return {{"out": TabularDataset(processed_rows, columns=columns)}}
\"\"\"
    with open(os.path.join(pkg_path, "nodes.py"), "w") as f:
        f.write(nodes_py.strip() + "\\n")
        
    # Write README.md
    readme = f\"\"\"# {name}

A custom FlowWeaver plugin.

## Installation

Register this plugin directory inside the FlowWeaver plugins directory, or deploy it.
\"\"\"
    with open(os.path.join(base_path, "README.md"), "w") as f:
        f.write(readme.strip() + "\\n")
        
    print(f"Successfully generated plugin template '{name}'!")
    print("Folder contents:")
    print(f"  - {name}/plugin.yaml")
    print(f"  - {name}/requirements.txt")
    print(f"  - {name}/{safe_name}/nodes.py")

def main():
    parser = argparse.ArgumentParser(description="FlowWeaver CLI developer assistant tool.")
    subparsers = parser.add_subparsers(dest="command", required=True)
    
    # create-plugin subcommand
    create_parser = subparsers.add_parser("create-plugin", help="Scaffold a new custom plugin template.")
    create_parser.add_argument("name", type=str, help="Name of the plugin directory to create.")
    
    args = parser.parse_args()
    
    if args.command == "create-plugin":
        create_plugin(args.name)

if __name__ == "__main__":
    main()
"""
with open(f"{sdk_dir}/flowweaver/sdk/cli.py", "w") as f:
    f.write(cli_py)

# 2. Overwrite packages/flowweaver_sdk/setup.py to include the entry point command mapping
setup_py = """from setuptools import setup, find_packages

setup(
    name="flowweaver-sdk",
    version="0.1.0",
    packages=find_packages(),
    install_packages=["pydantic>=2.0.0", "pyyaml>=6.0"],
    extras_require={
        "polars": ["polars>=1.0.0"],
        "arrow": ["pyarrow>=14.0.0"],
        "duckdb": ["duckdb>=0.9.0"],
    },
    entry_points={
        "console_scripts": [
            "flowweaver=flowweaver.sdk.cli:main",
        ]
    },
    author="FlowWeaver Team",
    description="Core developer SDK for writing FlowWeaver nodes and plugins",
    python_requires=">=3.8",
)
"""
with open(f"{sdk_dir}/setup.py", "w") as f:
    f.write(setup_py)

# 3. Refactor apps/api/app/engine/registry.py to scan a 'plugins' folder and load nodes dynamically
registry_py = """import os
import yaml
import importlib
import sys
from typing import List, Dict, Any, Optional
from flowweaver.sdk import Node, Port, Parameter
from app.engine.nodes.loaders import LoadCSVNode, LoadJSONNode
from app.engine.nodes.filters import FilterRowsNode
from app.engine.nodes.exports import WriteCSVNode
from app.engine.nodes.fallback import FallbackNode

class NodeRegistry:
    def __init__(self):
        self._nodes: Dict[str, Node] = {}
        self._loaded_plugins: List[Dict[str, Any]] = []

    def register(self, node: Node):
        self._nodes[node.id] = node

    def get(self, node_id: str) -> Optional[Node]:
        return self._nodes.get(node_id)

    def list_all(self) -> List[Node]:
        return list(self._nodes.values())

    def list_plugins(self) -> List[Dict[str, Any]]:
        return self._loaded_plugins

    def validate_config(self, node_id: str, config: Dict[str, Any]) -> tuple[bool, List[str]]:
        node = self.get(node_id)
        if not node:
            return False, [f"Node type '{node_id}' not found in registry."]
        
        errors = []
        for param in node.params_schema:
            val = config.get(param.key)
            if val is None:
                continue
                
            if param.type == "number" or param.type == "slider":
                if not isinstance(val, (int, float)):
                    errors.append(f"Parameter '{param.key}' must be a number.")
                else:
                    if param.min is not None and val < param.min:
                        errors.append(f"Parameter '{param.key}' must be >= {param.min}.")
                    if param.max is not None and val > param.max:
                        errors.append(f"Parameter '{param.key}' must be <= {param.max}.")
            elif param.type == "boolean":
                if not isinstance(val, bool):
                    errors.append(f"Parameter '{param.key}' must be a boolean.")
            elif param.type == "select":
                if param.options:
                    valid_values = {opt["value"] for opt in param.options}
                    if str(val) not in valid_values:
                        errors.append(f"Parameter '{param.key}' value '{val}' is not a valid option.")
                        
        return len(errors) == 0, errors

    def load_local_plugins(self, plugins_dir: str):
        \"\"\"Scan and load local plugins dynamically from plugin.yaml config files.\"\"\"
        if not os.path.exists(plugins_dir):
            os.makedirs(plugins_dir, exist_ok=True)
            return

        # Add plugins directory to sys.path to allow dynamic imports
        if plugins_dir not in sys.path:
            sys.path.insert(0, plugins_dir)

        print(f"Scanning for plugins in: {plugins_dir}...")
        for entry in os.listdir(plugins_dir):
            full_path = os.path.join(plugins_dir, entry)
            if os.path.isdir(full_path):
                yaml_path = os.path.join(full_path, "plugin.yaml")
                if os.path.exists(yaml_path):
                    try:
                        with open(yaml_path, "r") as f:
                            meta = yaml.safe_load(f)
                        
                        plugin_id = meta.get("id")
                        nodes_list = meta.get("nodes", [])
                        
                        # Add plugin directory to path so imports within it resolve correctly
                        if full_path not in sys.path:
                            sys.path.insert(0, full_path)
                            
                        # Load custom node classes declared in yaml
                        loaded_node_ids = []
                        for node_path in nodes_list:
                            module_name, class_name = node_path.rsplit(".", 1)
                            # Dynamically import module
                            mod = importlib.import_module(module_name)
                            node_class = getattr(mod, class_name)
                            
                            # Instantiate node
                            node_instance = node_class()
                            self.register(node_instance)
                            loaded_node_ids.append(node_instance.id)
                            print(f"Successfully loaded node '{node_instance.label}' [{node_instance.id}] from plugin '{plugin_id}'.")
                            
                        self._loaded_plugins.append({
                            "id": plugin_id,
                            "name": meta.get("name", plugin_id),
                            "version": meta.get("version", "0.1.0"),
                            "author": meta.get("author", "Unknown"),
                            "nodes": loaded_node_ids
                        })
                        
                    except Exception as e:
                        print(f"Failed to load plugin '{entry}': {str(e)}")

# Create global registry instance
registry = NodeRegistry()

# Register core implementations
registry.register(LoadCSVNode())
registry.register(LoadJSONNode())
registry.register(FilterRowsNode())
registry.register(WriteCSVNode())

# Seed fallback nodes to complete the 24 built-in list
fallback_node_ids = [
    ("http_fetch", "HTTP Fetch", "Loaders", "Fetch data from a REST endpoint", "Globe", "#4f86c6", [], [Port(id="out", label="response", type="any")]),
    ("load_sql", "SQL Query", "Loaders", "Run a SELECT against a database", "Database", "#4f86c6", [], [Port(id="out", label="rows", type="tabular")]),
    ("load_s3", "S3 Bucket", "Loaders", "List and read objects from S3", "Cloud", "#4f86c6", [], [Port(id="out", label="objects", type="any")]),
    ("load_images", "Load Images", "Loaders", "Read a directory of images", "ImageIcon", "#4f86c6", [], [Port(id="out", label="images", type="image")]),
    ("search_text", "Search Text", "Filters", "Regex/substring filter on a text column", "Search", "#c67a4f", [Port(id="in", label="rows", type="tabular", required=True)], [Port(id="out", label="matches", type="tabular")]),
    ("sample_rows", "Sample", "Filters", "Randomly sample N rows", "Shuffle", "#c67a4f", [Port(id="in", label="rows", type="tabular", required=True)], [Port(id="out", label="rows", type="tabular")]),
    ("select_columns", "Select Columns", "Transform", "Project a subset of columns", "Columns3", "#7a4fc6", [Port(id="in", label="rows", type="tabular", required=True)], [Port(id="out", label="rows", type="tabular")]),
    ("sort_rows", "Sort", "Transform", "Sort by a column", "ArrowUpDown", "#7a4fc6", [Port(id="in", label="rows", type="tabular", required=True)], [Port(id="out", label="rows", type="tabular")]),
    ("join_rows", "Join", "Transform", "Join two tables on a key", "GitMerge", "#7a4fc6", [Port(id="left", label="left", type="tabular", required=True), Port(id="right", label="right", type="tabular", required=True)], [Port(id="out", label="rows", type="tabular")]),
    ("split_col", "Split Column", "Transform", "Split a column by a delimiter", "Scissors", "#7a4fc6", [Port(id="in", label="rows", type="tabular", required=True)], [Port(id="out", label="rows", type="tabular")]),
    ("map_expr", "Map Expression", "Transform", "Compute a new column from an expression", "Wand2", "#7a4fc6", [Port(id="in", label="rows", type="any", required=True)], [Port(id="out", label="rows", type="any")]),
    ("dedup_exact", "Dedup Exact", "Dedup", "Remove exact duplicate rows", "Copy", "#4fc6a0", [Port(id="in", label="rows", type="tabular", required=True)], [Port(id="out", label="rows", type="tabular")]),
    ("dedup_fuzzy", "Dedup Fuzzy", "Dedup", "Fuzzy-match near duplicates", "Fingerprint", "#4fc6a0", [Port(id="in", label="rows", type="tabular", required=True)], [Port(id="out", label="rows", type="tabular")]),
    ("normalize", "Normalize", "Dedup", "Normalize whitespace, case, encoding", "SlidersHorizontal", "#4fc6a0", [Port(id="in", label="rows", type="any", required=True)], [Port(id="out", label="rows", type="any")]),
    ("tokenize", "Tokenize", "NLP", "Split text into tokens", "Type", "#c64f86", [Port(id="in", label="text", type="text", required=True)], [Port(id="out", label="tokens", type="any")]),
    ("detect_lang", "Detect Language", "NLP", "Identify text language", "Languages", "#c64f86", [Port(id="in", label="text", type="text", required=True)], [Port(id="out", label="text+lang", type="text")]),
    ("sentiment", "Sentiment", "NLP", "Classify text sentiment", "Sparkles", "#c64f86", [Port(id="in", label="text", type="text", required=True)], [Port(id="out", label="labeled", type="text")]),
    ("embed_text", "Embeddings", "NLP", "Content vector embeddings", "Hash", "#c64f86", [Port(id="in", label="text", type="text", required=True)], [Port(id="out", label="vectors", type="any")]),
    ("summarize", "Summarize", "NLP", "Abstractive summarization", "MessageSquare", "#c64f86", [Port(id="in", label="text", type="text", required=True)], [Port(id="out", label="summaries", type="text")]),
    ("write_json", "Write JSON", "Export", "Serialize records to JSON", "Download", "#c6b74f", [Port(id="in", label="rows", type="any", required=True)], []),
    ("webhook", "Send Webhook", "Export", "POST rows to an endpoint", "Send", "#c6b74f", [Port(id="in", label="rows", type="any", required=True)], []),
    ("upload_s3", "Upload S3", "Export", "Upload files to S3", "Upload", "#c6b74f", [Port(id="in", label="data", type="any", required=True)], []),
]

for node_id, label, cat, desc, icon, color, inputs, outputs in fallback_node_ids:
    fallback_node = FallbackNode(node_id)
    fallback_node.label = label
    fallback_node.category = cat
    fallback_node.description = desc
    fallback_node.icon = icon
    fallback_node.color = color
    fallback_node.inputs = inputs
    fallback_node.outputs = outputs
    fallback_node.params_schema = []
    registry.register(fallback_node)

# Trigger dynamic loading scanning of "plugins" directory in main.py entry
"""
with open(f"apps/api/app/engine/registry.py", "w") as f:
    f.write(registry_py)

print("Scaffolding DX configurations completed successfully!")
